### ISSUE TITLE
operation

### ISSUE THREAD

**Issue by yw2e** [jilt/discord-minting-bot#2]
hi, please can the read.me file be more explanative, also the link for deploying the bafwallet in the USAGE.md file does not work.  can something be done about that too.  A reply would be sincerely appreciated. thank you very much

**Comment by yw2e** [comment]
hi, please can the read.me file be more explanative, also the link for deploying the bafwallet in the USAGE.md file does not work. can something be done about that too. A reply would be sincerely appreciated. thank you very much

**Comment by jilt** [comment]
Hi I suggest you guys to go ask into the main bafwallet repository, I've cloned the repository only for reference.
